// const getNameRegex = /(^[\s|\w|\p{L}]\D+),.+/gu; // converte entradas csv para array de nome completo
// Usar a busca do vscode no modo regez e substituir por "$1",

// coloca a primeira letra de cada palavra em uppercase
// function capitalize(text) {
//   return text.charAt(0).toUpperCase() + text.slice(1).toLowerCase();
// }

// interface People {
//   accountNames: string[];
//   name: {
//     simplename: string,
//     fullname: string,
//     firstname: string,
//     lastname: string,
//     nickname?: string,
//   };
//   type: "Membro" | "Visitante" | "Congregado" | "Outro";
//   status:
//     | "Ativo"
//     | "Regular"
//     | "Disciplinado"
//     | "Excluído"
//     | "Desligado"
//     | "Inativo";
//   locale?:
//     | "Quixadá"
//     | "Banabuiú"
//     | "Ibaretama"
//     | "Triunfo"
//     | "Serra do Estêvão"
//     | "Comunidade Esperança"
//     | "Café Campestre";
//   birthdate?: Date;
//   age?: number;
//   phone?: string;
// }

// função para formatar nome a partir do account names
// JSON.stringify(
//   people.map((p) => {
//     const [first, last] = p.accountNames[0].split(" ");
//     const firstname = p.name.firstname || capitalize(first);
//     const lastname = p.name.lastname || capitalize(last);
//     const fullname = `${firstname} ${lastname}`;
//     return {
//       ...p,
//       name: {
//         ...p.name,
//         fullname,
//         firstname,
//         lastname,
//       },
//     };
//   }),
//   " ",
//   2
// );

// mapeando csv para array de objetos
// csv.map(({NOME_COMPLETO, NOME_SIMPLES, NOME, SOBRENOME, MEMBRO, CONGREGACAO, LOCAL, STATUS}, index) => {
//   return {
//       id: index,
//       accountName: [NOME_COMPLETO.split(' ').length > 2 ? NOME_COMPLETO : undefined],
//       name: {
//           simplename: NOME_SIMPLES,
//           fullname: NOME_COMPLETO,
//           firstname: NOME,
//           lastname: SOBRENOME,
//       },
//       type: MEMBRO == 'Sim' ? 'Membro' : 'Visitor',
//       status: STATUS,
//       locale: CONGREGACAO
//   }
// })

// Início da função para formatar nome a partir do account names
// prerequisitos é converter o csv para json e mudar os nomes das props

// entries.map(({ descricao, ...rest }) => {
//   const user = people.find(({ accountNames }) =>
//     accountNames.includes(descricao.trim())
//   );
//   return {
//     ...rest,
//     descricao: user ? user?.name?.simplename : descricao,
//     categoria: user?.type === "Membro" ? "Dízimo" : "Oferta",
//   };
// });

const people = [
  {
    accountNames: [],
    name: {
      fullname: "Alex Sandro",
      simplename: "Alex Sandro",
      firstname: "Alex",
      lastname: "Sandro",
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Triunfo",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Francisco Alex",
      simplename: "Francisco Alex",
      firstname: "Francisco",
      lastname: "Alex",
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Triunfo",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Ana Ester",
      simplename: "Ana Ester",
      firstname: "Ana",
      lastname: "Ester",
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Antônia Alzenir da Silva Ferreira"],
    name: {
      fullname: "Antônia Alzenir da Silva Ferreira",
      simplename: "Alzenir Ferreira",
      firstname: "Alzenir",
      lastname: "Ferreira",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Antônia Daiana Cândido de Almeida"],
    name: {
      fullname: "Antônia Daiana Cândido de Almeida",
      simplename: "Daiana de Almeida",
      firstname: "Daiana",
      lastname: "de Almeida",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Banabuiú",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Antonia Pereira de Lima"],
    name: {
      fullname: "Antonia Pereira de Lima",
      simplename: "Antonia Pereira",
      firstname: "Antonia",
      lastname: "Pereira",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Maria Auzenir Campos Rodrigues"],
    name: {
      fullname: "Maria Auzenir Campos Rodrigues",
      simplename: "Auzenir Campos",
      firstname: "Auzenir",
      lastname: "Campos",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Carlos Breno Sousa Dantas"],
    name: {
      fullname: "Carlos Breno Sousa Dantas",
      simplename: "Breno Dantas",
      firstname: "Breno",
      lastname: "Dantas",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Cheila da Silva Ferreira"],
    name: {
      fullname: "Cheila da Silva Ferreira",
      simplename: "Cheila Ferreira",
      firstname: "Cheila",
      lastname: "Ferreira",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Cleysna Maria Rodrigues Pinto"],
    name: {
      fullname: "Cleysna Maria Rodrigues Pinto",
      simplename: "Cleysna Rodrigues",
      firstname: "Cleysna",
      lastname: "Rodrigues",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Banabuiú",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Maria Daniele de Lima Sousa Oliveira"],
    name: {
      fullname: "Maria Daniele de Lima Sousa Oliveira",
      simplename: "Daniele Oliveira",
      firstname: "Daniele",
      lastname: "Oliveira",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Banabuiú",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Edmar Tavares Lima Junior"],
    name: {
      fullname: "Edmar Tavares Lima Junior",
      simplename: "Junior Tavares",
      firstname: "Junior",
      lastname: "Tavares",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Banabuiú",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Emerson Lima de Oliveira"],
    name: {
      fullname: "Emerson Lima de Oliveira",
      simplename: "Emerson Oliveira",
      firstname: "Emerson",
      lastname: "Oliveira",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Ezequiel Alves Lobo"],
    name: {
      fullname: "Ezequiel Alves Lobo",
      simplename: "Ezequiel Lobo",
      firstname: "Ezequiel",
      lastname: "Lobo",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Fernanda Albuquerque de Abreu"],
    name: {
      fullname: "Fernanda Albuquerque de Abreu",
      simplename: "Fernanda Abreu",
      firstname: "Fernanda",
      lastname: "Abreu",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Flávio Ferreira Barbosa"],
    name: {
      fullname: "Flávio Ferreira Barbosa",
      simplename: "Flávio Barbosa",
      firstname: "Flávio",
      lastname: "Barbosa",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Francisco Amaro de Almeida Junior"],
    name: {
      fullname: "Francisco Amaro de Almeida Junior",
      simplename: "Amaro Junior",
      firstname: "Amaro",
      lastname: "Junior",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Banabuiú",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Francisco Mateus da Silva"],
    name: {
      fullname: "Francisco Mateus da Silva",
      simplename: "Matheus da Silva",
      firstname: "Matheus",
      lastname: "da Silva",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Banabuiú",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Francisco Nildemar da Silva",
      simplename: "Nildemar da Silva",
      firstname: "Nildemar",
      lastname: "da Silva",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Banabuiú",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Gedyson de Oliveira Lima"],
    name: {
      fullname: "Gedyson de Oliveira Lima",
      simplename: "Gedyson Lima",
      firstname: "Gedyson",
      lastname: "Lima",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["José Glaudevan Lima da Silva"],
    name: {
      fullname: "José Glaudevan Lima da Silva",
      simplename: "Glaudevan da Silva",
      firstname: "Glaudevan",
      lastname: "da Silva",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Gleiziane Muniz Da Silva Pinto"],
    name: {
      fullname: "Gleiziane Muniz Da Silva Pinto",
      simplename: "Gleiziane Pinto",
      firstname: "Gleiziane",
      lastname: "Pinto",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Hélio da Silva Almeida"],
    name: {
      fullname: "Hélio da Silva Almeida",
      simplename: "Hélio Almeida",
      firstname: "Hélio",
      lastname: "Almeida",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Isabel Torres do Nascimento"],
    name: {
      fullname: "Isabel Torres do Nascimento",
      simplename: "Isabel Torres",
      firstname: "Isabel",
      lastname: "Torres",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Banabuiú",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Jefferson Diego Mendes da Silva"],
    name: {
      fullname: "Jefferson Diego Mendes da Silva",
      simplename: "Jefferson da Silva",
      firstname: "Jefferson",
      lastname: "da Silva",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "João Ferreira",
      simplename: "João Ferreira",
      firstname: "João",
      lastname: "Ferreira",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Jônatas Fragoso de Almeida"],
    name: {
      fullname: "Jônatas Fragoso de Almeida",
      simplename: "Jônatas Fragoso",
      firstname: "Jônatas",
      lastname: "Fragoso",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Banabuiú",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["José de Souza Santos"],
    name: {
      fullname: "José de Souza Santos",
      simplename: "José de Souza",
      firstname: "José",
      lastname: "de Souza",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["José Felipe da Silva"],
    name: {
      fullname: "José Felipe da Silva",
      simplename: "José Felipe",
      firstname: "José",
      lastname: "Felipe",
      nickname: "Zé Felipe",
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["José Valdeci Venâncio Pereira", "Natanael Barbosa Pereira"],
    name: {
      fullname: "José Valdeci Venâncio Pereira",
      simplename: "José Valdeci",
      firstname: "José",
      lastname: "Valdeci",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "José Eloe da Silva",
      simplename: "José Eloe",
      firstname: "José",
      lastname: "Eloe",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Júlia",
      simplename: "Ana Júlia",
      firstname: "Ana",
      lastname: "Júlia",
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Juliana Oliveira dos Santos"],
    name: {
      fullname: "Juliana Oliveira dos Santos",
      simplename: "Juliana Oliveira",
      firstname: "Juliana",
      lastname: "Oliveira",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["José Edvaldo de Souza Junior"],
    name: {
      fullname: "José Edvaldo de Souza Junior",
      simplename: "Junior de Souza",
      firstname: "Junior",
      lastname: "de Souza",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Kamilly Rodrigues de Menezes"],
    name: {
      fullname: "Kamilly Rodrigues de Menezes",
      simplename: "Kamilly Rodrigues",
      firstname: "Kamilly",
      lastname: "Rodrigues",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Karine Rodrigues de Menezes"],
    name: {
      fullname: "Karine Rodrigues de Menezes",
      simplename: "Karine Rodrigues",
      firstname: "Karine",
      lastname: "Rodrigues",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Kerem Fragoso Almeida",
      simplename: "Kerem Fragoso",
      firstname: "Kerem",
      lastname: "Fragoso",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["José Lauro de Sousa"],
    name: {
      fullname: "José Lauro de Sousa",
      simplename: "José Lauro",
      firstname: "José",
      lastname: "Lauro",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Leilane Muniz Carlos Lima"],
    name: {
      fullname: "Leilane Muniz Carlos Lima",
      simplename: "Leilane Lima",
      firstname: "Leilane",
      lastname: "Lima",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Letícia Muniz Carlos Maia"],
    name: {
      fullname: "Letícia Muniz Carlos Maia",
      simplename: "Letícia Muniz",
      firstname: "Letícia",
      lastname: "Muniz",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Lindeci Pereira Araújo Duarte"],
    name: {
      fullname: "Lindeci Pereira Araújo Duarte",
      simplename: "Lindeci Duarte",
      firstname: "Lindeci",
      lastname: "Duarte",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Luana Kissila Rodrigues Rufino Lima"],
    name: {
      fullname: "Luana Kissila Rodrigues Rufino Lima",
      simplename: "Luana Lima",
      firstname: "Luana",
      lastname: "Lima",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Luiz Everton Rodrigues Silva"],
    name: {
      fullname: "Luiz Everton Rodrigues Silva",
      simplename: "Luiz Everton",
      firstname: "Luiz",
      lastname: "Everton",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Luiza Ferreira Tavares"],
    name: {
      fullname: "Luiza Ferreira Tavares",
      simplename: "Luiza Tavares",
      firstname: "Luiza",
      lastname: "Tavares",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Paulo Lutyele Diogo Facundo"],
    name: {
      fullname: "Paulo Lutyele Diogo Facundo",
      simplename: "Lutyele Facundo",
      firstname: "Lutyele",
      lastname: "Facundo",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Maria Dilma",
      simplename: "Maria Dilma",
      firstname: "Maria",
      lastname: "Dilma",
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Triunfo",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Márcio Barros",
      simplename: "Márcio Barros",
      firstname: "Márcio",
      lastname: "Barros",
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Triunfo",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Maria da Glória Machado"],
    name: {
      fullname: "Maria da Glória Machado",
      simplename: "Glória Machado",
      firstname: "Glória",
      lastname: "Machado",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Banabuiú",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Maria das Graças Rodrigues Barbosa"],
    name: {
      fullname: "Maria das Graças Rodrigues Barbosa",
      simplename: "Graça Barbosa",
      firstname: "Graça",
      lastname: "Barbosa",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Maria de Fátima Oliveira (Almeida) Rangel",
      simplename: "Fátima Oliveira",
      firstname: "Fátima",
      lastname: "Oliveira",
      nickname: null,
    },
    type: "Membro",
    status: "Regular",
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Maria do Carmo Ferreira Sousa"],
    name: {
      fullname: "Maria do Carmo Ferreira Sousa",
      simplename: "Maria do Carmo Ferreira",
      firstname: "Maria do Carmo",
      lastname: "Ferreira",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Maria do Carmo Rodrigues Lima"],
    name: {
      fullname: "Maria do Carmo Rodrigues Lima",
      simplename: "Maria do Carmo Rodrigues",
      firstname: "Maria do Carmo",
      lastname: "Rodrigues",
      nickname: "Maria do Carmo (Café)",
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Maria Eduarda",
      simplename: "Maria Eduarda",
      firstname: "Maria",
      lastname: "Eduarda",
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Maria Rafaela Alves Lobo"],
    name: {
      fullname: "Maria Rafaela Alves Lobo",
      simplename: "Rafaela Alves",
      firstname: "Rafaela",
      lastname: "Alves",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Maria Rosa Oliveira Silva"],
    name: {
      fullname: "Maria Rosa Oliveira Silva",
      simplename: "Rosa Oliveira",
      firstname: "Rosa",
      lastname: "Oliveira",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Banabuiú",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Maria Rosenir Barbosa Pereira",
      simplename: "Maria Rosenir",
      firstname: "Maria",
      lastname: "Rosenir",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Norma Antônia Almeida",
      simplename: "Norma Almeida",
      firstname: "Norma",
      lastname: "Almeida",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Paulo Augusto",
      simplename: "Paulo Augusto",
      firstname: "Paulo",
      lastname: "Augusto",
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Priscila Noronha Cavalcante"],
    name: {
      fullname: "Priscila Noronha Cavalcante",
      simplename: "Priscila Noronha",
      firstname: "Priscila",
      lastname: "Noronha",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Rebeca Rabelo Soares"],
    name: {
      fullname: "Rebeca Rabelo Soares",
      simplename: "Rebeca Rabelo",
      firstname: "Rebeca",
      lastname: "Rabelo",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Rita Monteiro da Silva Sousa"],
    name: {
      fullname: "Rita Monteiro da Silva Sousa",
      simplename: "Rita Monteiro",
      firstname: "Rita",
      lastname: "Monteiro",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Romualdo Pereira de Lima"],
    name: {
      fullname: "Romualdo Pereira de Lima",
      simplename: "Romualdo Pereira",
      firstname: "Romualdo",
      lastname: "Pereira",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Salete Silva Barbosa"],
    name: {
      fullname: "Salete Silva Barbosa",
      simplename: "Salete Barbosa",
      firstname: "Salete",
      lastname: "Barbosa",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Thais Axiley Cavalcante Silva"],
    name: {
      fullname: "Thais Axiley Cavalcante Silva",
      simplename: "Thais Cavalcante",
      firstname: "Thais",
      lastname: "Cavalcante",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Taís da Silva Ferreira"],
    name: {
      fullname: "Taís da Silva Ferreira",
      simplename: "Taís da Silva",
      firstname: "Taís",
      lastname: "da Silva",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Ubirajara Vaz Rangel"],
    name: {
      fullname: "Ubirajara Vaz Rangel",
      simplename: "Ubirajara Rangel",
      firstname: "Ubirajara",
      lastname: "Rangel",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Vanessa Silva de Aquino"],
    name: {
      fullname: "Vanessa Silva de Aquino",
      simplename: "Vanessa Silva",
      firstname: "Vanessa",
      lastname: "Silva",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Banabuiú",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Maria Evangelista de Lima"],
    name: {
      fullname: "Maria Evangelista de Lima",
      simplename: "Maria Evangelista",
      firstname: "Maria",
      lastname: "Evangelista",
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Francisca da Silva"],
    name: {
      fullname: "Francisca da Silva",
      simplename: "Francisca da Silva",
      firstname: "Francisca",
      lastname: "da Silva",
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Lúcia Fátima Lima"],
    name: {
      fullname: "Lúcia Fátima Lima",
      simplename: "Lúcia Lima",
      firstname: "Lúcia",
      lastname: "Lima",
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Kathrine Nobre",
      simplename: "Kathrine Nobre",
      firstname: "Kathrine",
      lastname: "Nobre",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Adriana",
      simplename: "Adriana Sousa",
      firstname: "Adriana",
      lastname: "Sousa",
      nickname: null,
    },
    type: "Membro",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Luciana Alves",
      simplename: "Luciana Alves",
      firstname: "Luciana",
      lastname: "Alves",
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Ivonete Fragoso Vieira de Almeida",
      simplename: "Ivonete Fragoso",
      firstname: "Ivonete",
      lastname: "Fragoso",
      nickname: null,
    },
    type: "Membro",
    status: "Regular",
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Matheus De Lima Maciel"],
    name: {
      fullname: "Matheus de Lima Maciel",
      simplename: "Matheus Lima",
      firstname: "Matheus",
      lastname: "Lima",
      nickname: null,
    },
    type: "Membro",
    status: "Ativo",
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Antônio Alessandro Aprigio Brito",
      simplename: "Alessandro Brito",
      firstname: "Alessandro",
      lastname: "Brito",
      nickname: null,
    },
    type: "Membro",
    status: "Regular",
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Luciana Basílio De Sousa",
      simplename: "Luciana Sousa",
      firstname: "Luciana",
      lastname: "Sousa",
      nickname: null,
    },
    type: "Membro",
    status: "Regular",
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Maria de Fátima Souza Lima",
      simplename: "Fátima Lima",
      firstname: "Fátima",
      lastname: "Lima",
      nickname: null,
    },
    type: "Membro",
    status: "Regular",
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: ["Marcos Gleidson Sousa Santos"],
    name: {
      fullname: "Marcos",
      simplename: "Marcos Sousa",
      firstname: "Marcos",
      lastname: "Sousa",
      nickname: null,
    },
    type: "Membro",
    status: "Regular",
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Janete Fragoso Vieira de Almeida",
      simplename: "Janete Fragoso",
      firstname: "Janete",
      lastname: "Fragoso",
      nickname: null,
    },
    type: "Membro",
    status: "Regular",
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "José Anchieta De Almeida",
      simplename: "José Anchieta",
      firstname: "José",
      lastname: "Anchieta",
      nickname: "Dedé",
    },
    type: "Membro",
    status: "Regular",
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Rayanderson Saraiva",
      simplename: null,
      firstname: "Rayanderson",
      lastname: "Saraiva",
      nickname: null,
    },
    type: "Congregado",
    status: "Ativo",
    locale: null,
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Natanael Barbosa",
      simplename: null,
      firstname: "Natanael",
      lastname: "Barbosa",
      nickname: null,
    },
    type: "Congregado",
    status: "Ativo",
    locale: null,
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Francisco Jakson Da Silva Sousa",
      simplename: "Francisco Jakson",
      firstname: "Francisco",
      lastname: "Jakson",
      nickname: null,
    },
    type: "Visitante",
    status: "Ativo",
    locale: null,
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Henok Pontes",
      simplename: "Henok Pontes",
      firstname: "Henok",
      lastname: "Pontes",
      nickname: null,
    },
    type: "Congregado",
    status: "Ativo",
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Dara Alves Vieira Fragoso",
      simplename: "Dara Fragoso",
      firstname: "Dara",
      lastname: "Fragoso",
      nickname: null,
    },
    type: "Membro",
    status: "Regular",
    locale: "Banabuiú",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Arley Gomes De Sousa",
      simplename: "Arley Gomes",
      firstname: "Arley",
      lastname: "Gomes",
      nickname: null,
    },
    type: "Membro",
    status: "Regular",
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Sarah Ferreira",
      simplename: null,
      firstname: "Sarah",
      lastname: "Ferreira",
      nickname: null,
    },
    type: "Congregado",
    status: "Ativo",
    locale: null,
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Elizangela Rodrigues de Almeida",
      simplename: "Elizangela de Almeida",
      firstname: "Elizangela",
      lastname: "Almeida",
      nickname: null,
    },
    type: "Membro",
    status: "Regular",
    locale: "Banabuiú",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Ismael Barbosa de Sousa",
      simplename: "Ismael Barbosa",
      firstname: "Ismael",
      lastname: "Barbosa",
      nickname: null,
    },
    type: "Membro",
    status: "Ativo",
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Elisfábio Brito Duarte",
      simplename: "Elisfábio Duarte",
      firstname: "Elisfábio",
      lastname: "Brito",
      nickname: null,
    },
    type: "Membro",
    status: "Regular",
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Antônio Morais",
      simplename: null,
      firstname: "Antônio",
      lastname: "Morais",
      nickname: null,
    },
    type: "Congregado",
    status: "Ativo",
    locale: null,
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Itzhak Rubens Santos Oliveira",
      simplename: "Itzhak Oliveira",
      firstname: "Itzhak",
      lastname: "Oliveira",
      nickname: null,
    },
    type: "Membro",
    status: "Regular",
    locale: "Banabuiú",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Edinei Lourenco Da Silva",
      simplename: "Edinei Lourenço",
      firstname: "Edinei",
      lastname: "Lourenço",
      nickname: null,
    },
    type: "Membro",
    status: "Regular",
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Francisco Weliton Da Silva",
      simplename: "Francisco Weliton",
      firstname: "Francisco",
      lastname: "Weliton",
      nickname: null,
    },
    type: "Membro",
    status: "Regular",
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Isaac Bruno Brandão Maia Lima",
      simplename: "Isaac Lima",
      firstname: "Isaac",
      lastname: "Lima",
      nickname: null,
    },
    type: "Membro",
    status: "Regular",
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "José Rodson",
      simplename: null,
      firstname: "José",
      lastname: "Rodson",
      nickname: null,
    },
    type: "Visitante",
    status: "Ativo",
    locale: null,
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Natan Nobre Chaves",
      simplename: "Natan Nobre",
      firstname: "Natan",
      lastname: "Nobre",
      nickname: null,
    },
    type: "Membro",
    status: "Regular",
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Edson Carlos Pinto Filho",
      simplename: "Edson Carlos",
      firstname: "Edson",
      lastname: "Carlos",
      nickname: null,
    },
    type: "Membro",
    status: "Regular",
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Igreja Batista",
      simplename: null,
      firstname: "Igreja",
      lastname: "Batista",
      nickname: null,
    },
    type: "Outro",
    status: "Ativo",
    locale: null,
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Palti Talmai Rodrigues De Oliveira",
      simplename: "Palti Talmai",
      firstname: "Palti",
      lastname: "Talmai",
      nickname: null,
    },
    type: "Membro",
    status: "Regular",
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Albert",
      simplename: "Albert",
      firstname: "Albert",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Álvaro",
      simplename: "Álvaro",
      firstname: "Álvaro",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Banabuiú",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Arthur",
      simplename: "Arthur",
      firstname: "Arthur",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Cainã",
      simplename: "Cainã",
      firstname: "Cainã",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Daniel",
      simplename: "Daniel",
      firstname: "Daniel",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Triunfo",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "David",
      simplename: "David",
      firstname: "David",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Banabuiú",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Débora",
      simplename: "Débora",
      firstname: "Débora",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Emanuelle",
      simplename: "Emanuelle",
      firstname: "Emanuelle",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Banabuiú",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Ester",
      simplename: "Ester",
      firstname: "Ester",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Banabuiú",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Ester",
      simplename: "Ester",
      firstname: "Ester",
      lastname: null,
      nickname: "Ester (Sara)",
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Eudimar",
      simplename: "Eudimar",
      firstname: "Eudimar",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Eunice",
      simplename: "Eunice",
      firstname: "Eunice",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Eva",
      simplename: "Eva",
      firstname: "Eva",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Banabuiú",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Gabriel",
      simplename: "Gabriel",
      firstname: "Gabriel",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Gustavo",
      simplename: "Gustavo",
      firstname: "Gustavo",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Triunfo",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Igor",
      simplename: "Igor",
      firstname: "Igor",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Banabuiú",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Isabela",
      simplename: "Isabela",
      firstname: "Isabela",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Triunfo",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Isabella",
      simplename: "Isabella",
      firstname: "Isabella",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Triunfo",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Isabely",
      simplename: "Isabely",
      firstname: "Isabely",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Juliene",
      simplename: "Juliene",
      firstname: "Juliene",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Triunfo",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Leoci",
      simplename: "Leoci",
      firstname: "Leoci",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Levi",
      simplename: "Levi",
      firstname: "Levi",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Michael",
      simplename: "Michael",
      firstname: "Michael",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Nazira",
      simplename: "Nazira",
      firstname: "Nazira",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Triunfo",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Otávio",
      simplename: "Otávio",
      firstname: "Otávio",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Triunfo",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Samuel",
      simplename: "Samuel",
      firstname: "Samuel",
      lastname: null,
      nickname: "(Sara)",
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Samuel",
      simplename: "Samuel",
      firstname: "Samuel",
      lastname: null,
      nickname: "(Elisfábio)",
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Sandra",
      simplename: "Sandra",
      firstname: "Sandra",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Sara",
      simplename: "Sara",
      firstname: "Sara",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Thaiza",
      simplename: "Thaiza",
      firstname: "Thaiza",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Triunfo",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Valéria",
      simplename: "Valéria",
      firstname: "Valéria",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Vitor",
      simplename: "Vitor",
      firstname: "Vitor",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Walentina",
      simplename: "Walentina",
      firstname: "Walentina",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Triunfo",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Fabio",
      simplename: "Fabio",
      firstname: "Fabio",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Berivaldo",
      simplename: "Berivaldo",
      firstname: "Berivaldo",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Krisliane",
      simplename: "Krisliane",
      firstname: "Krisliane",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
  {
    accountNames: [],
    name: {
      fullname: "Príscila",
      simplename: "Príscila",
      firstname: "Príscila",
      lastname: null,
      nickname: null,
    },
    type: "Visitante",
    status: null,
    locale: "Quixadá",
    birthdate: null,
    age: null,
    phone: null,
  },
];

module.exports = {
  people,
  // members,
  // visitors,
  // attendees,
};

// TEMPORARY
// removeDistinctByProps(people.map(({name}) => name), ['firstname']).filter(({lastname}) => lastname)
// removeDistinctByProps(people.map(({name}) => name), ['firstname', 'lastname']).filter(({lastname}) => lastname)
// removeDistinctByProps(people.map(({name}) => name), ['firstname', 'lastname']).filter(({lastname}) => lastname)
// removeDistinctByProps(people.map(({name}) => name), ['firstname']).filter(({lastname}) => lastname)
// removeDistinctByProps(people.map(({name}) => name), ['firstname']).filter(({lastname}) => !lastname)
// removeDistinctByProps(people.map(({name}) => name), ['firstname']).filter(({lastname}) => lastname)
// const removeDistinctByProps = (arr, props) => {
//   return arr.filter((item, index) => arr.findIndex(obj => props.every(prop => obj[prop] === item[prop])) !== index);
// };

// function adaptToPeopleInterface(data) {
//   const adaptedData = data.map((person) => {
//     const adaptedPerson = {
//       accountNames: person.accountNames || [],
//       name: {
//         fullname: person.name?.fullname || null,
//         simplename: person.name?.simplename || null,
//         firstname: person.name?.firstname || null,
//         lastname: person.name?.lastname || null,
//         nickname: person.name?.nickname || null,
//       },
//       type: person.type || null,
//       status: person.status || null,
//       locale: person.locale || null,
//       birthdate: person.birthdate || null,
//       age: person.age || null,
//       phone: person.phone || null,
//     };
//     return adaptedPerson;
//   });

//   return adaptedData;
// }

// function sortByEmptyProperties(data) {
//   const emptyPropertiesCount = obj => {
//     let count = 0;
//     for (let key in obj) {
//       if (obj.hasOwnProperty(key) && obj[key] === null) {
//         count++;
//       }
//     }
//     return count;
//   };

//   const sortedData = data.sort((a, b) => {
//     const emptyCountA = emptyPropertiesCount(a);
//     const emptyCountB = emptyPropertiesCount(b);
//     return emptyCountA - emptyCountB;
//   });

//   return sortedData;
// }

// const sortedPeople = sortByEmptyProperties(people);
// console.log(sortedPeople);
